package com.example.entshptapplication.models

data class FindNaryadModel(
    val id: Int,
    val shet: String,
    val shetDateStr: String?,
    val naryadNum: String,
    val numInOrder: Int,
    val doorName: String,
    val open: String,
    val nalichnik: String,
    val dovod: String,
    val ral: String,
    val markirovka: String,
    val doorSize: String,
    val note: String?,
    val shtild: String?,
    val svarkaComplite: Boolean,
    val svarkaCompliteFio: String?,
    val svarkaCost: Float,
    val svarkaCompliteDateStr: String?,
    val sborkaComplite: Boolean,
    val sborkaCompliteFio: String?,
    val sborkaCost: Float,
    val sborkaCompliteDateStr: String?,
    val colorComplite: Boolean,
    val colorCompliteFio: String?,
    val colorCost: Float,
    val colorCompliteDateStr: String?,
    val upakComplite: Boolean,
    val upakCompliteFio: String?,
    val upakCost: Float,
    val upakCompliteDateStr: String?,
    val shptComplite: Boolean,
    val shptCompliteFio: String?,
    val shptCost: Float,
    val shptCompliteDateStr: String?,
    var onChecked: Boolean = false
)
